// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chirps.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const chirpAdd = `-- name: ChirpAdd :one
INSERT INTO chirps (id, created_at, updated_at, body, user_id)
VALUES (
    gen_random_uuid(), NOW(), NOW(), $1, $2
)
RETURNING id, created_at, updated_at, body, user_id
`

type ChirpAddParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) ChirpAdd(ctx context.Context, arg ChirpAddParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, chirpAdd, arg.Body, arg.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const chirpDelete = `-- name: ChirpDelete :exec
DELETE FROM chirps
WHERE id = $1
`

func (q *Queries) ChirpDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, chirpDelete, id)
	return err
}

const chirpGet = `-- name: ChirpGet :one
SELECT id, created_at, updated_at, body, user_id FROM chirps
WHERE id = $1 LIMIT 1
`

func (q *Queries) ChirpGet(ctx context.Context, id uuid.UUID) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, chirpGet, id)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const chirpsGet = `-- name: ChirpsGet :many
SELECT id, created_at, updated_at, body, user_id FROM chirps
WHERE (COALESCE($1::uuid, '00000000-0000-0000-0000-000000000000') = '00000000-0000-0000-0000-000000000000' OR user_id = $1)
ORDER BY created_at ASC
`

func (q *Queries) ChirpsGet(ctx context.Context, dollar_1 uuid.UUID) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, chirpsGet, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
